### makefile for Project Generator

CPP_SOURCES+=sources/projectGenerator.cpp

CPP:=g++

EXE_NAME:=ProjectGenerator.exe

RM_CMD:=rm -rf

all:
	$(CPP) $(CPP_SOURCES) -o $(EXE_NAME)

clean:
	$(RM_CMD) $(EXE_NAME)
	